server:
  port: 8085

spring:
  datasource:
    url: jdbc:h2:mem:user-service-db;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: true
        format_sql: true


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        web: info
        data: DEBUG








